# Generated by Django 3.2.6 on 2021-08-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210824_1630'),
        ('stores', '0002_auto_20210824_1630'),
        ('products', '0002_auto_20210824_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_item', to='products.drug'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_item', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='stores.store'),
        ),
    ]
