# Generated by Django 3.2.6 on 2021-08-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
