# Generated by Django 3.2.6 on 2021-08-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_drug_manufacturer'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.drug')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.store')),
            ],
        ),
    ]
