# Generated by Django 3.2.6 on 2021-08-24 11:30

import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210824_1630'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='address_uz',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.AddField(
            model_name='store',
            name='address_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(41.0, 69.0), geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Remain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('phone', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='remains', to='products.drug')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='remains', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=120)),
                ('name_ru', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='childs', to='stores.region')),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stores.region'),
        ),
    ]
