# Generated by Django 3.2.6 on 2021-08-10 09:52

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(41.0, 69.0), geography=True, null=True, srid=4326),
        ),
    ]
