# Generated by Django 3.2.6 on 2021-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='other',
            field=models.BooleanField(default=False),
        ),
    ]
